#!/bin/sh
# px-ip — match IPv4 addresses
# Usage:   <command> | px -e ip
awk '{
    line = $0
    offset = 0
    while (match(line, /[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/)) {
        start = offset + RSTART - 1
        printf "%d:%d:%d\n", NR, start, start + RLENGTH
        offset = start + RLENGTH
        line = substr(line, RSTART + RLENGTH)
    }
}'
